apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "az-dns-forwarder.name" . }}
  labels:
    {{- include "az-dns-forwarder.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "az-dns-forwarder.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
  template:
    metadata:
      labels:
        {{- include "az-dns-forwarder.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "az-dns-forwarder.name" . }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "ghcr.io/aisotag/docker/az-dns-forwarder:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 53
              protocol: UDP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - {{ include "az-dns-forwarder.name" . }}
                topologyKey: "kubernetes.io/hostname"
