name: Build and push Container
on:
  push:
  #  paths:
  #  - 'src/'
  schedule:
    - cron:  '0 5 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Chechout Code
    - uses: docker/build-push-action@v1
      name: Build Container
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: src/
        registry: docker.pkg.github.com
        repository: /whiteducksoftware/az-dns-forwarder/az-dns-forwarder
        tags: latest
        tag_with_sha: true
        add_git_labels: true
